source/repos/WTCnt/WTCnt/Controllers/WorkTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WTCnt.Models;
using Task = WTCnt.Models.Task;

namespace WTCnt.Controllers
{
    public class WorkTasksController : Controller
    {
        private readonly TaskContext _context;
        private readonly UsrContext _usrContext;
        public WorkTasksController(TaskContext context, UsrContext usr)
        {
            _context = context;
            _usrContext = usr;
        }

        // GET: Tasks
        public async Task<IActionResult> Index(int? id)
        {
            if (_context.Task.ToList().Find(t => t.EndDate == null && t.Type != "Работа" && t.UserOwner == int.Parse(HttpContext.User.Identities.ToList()[0].Name)) == null)
            {
                MainViewModel model = new MainViewModel();
                var tasks = _context.Task.ToList().FindAll(t => t.Type == "Работа" && t.UserOwner == int.Parse(HttpContext.User.Identities.ToList()[0].Name));
                List<Task> t = tasks;
                switch (id)
                {
                    case 1:
                        t = tasks.OrderBy(t => t.CreationDate).ToList();
                        break;
                    case 2:
                        t = tasks.OrderBy(t => t.EndDate).ToList();
                        break;
                    case 3:
                        t = tasks.OrderBy(t => t.Comment).ToList();
                        break;
                    case 4:
                        t = tasks.OrderBy(t => t.Done).ToList();
                        break;
                }
                model = new MainViewModel { Task = new Task(), Tasks = t, IsActiveTaskExists = false };
                return View(model);
            }
            else
            {
                return RedirectToAction("Chill");
            }
        }
        public async Task<IActionResult> IndexForAdmin(int? id)
        {
            MainViewModel model = new MainViewModel();
            var tasks = _context.Task.ToList().FindAll(t => t.Type == "Работа");
            List<Task> t = tasks;
            if (id != null)
            {
                switch (id)
                {
                    case 1:
                        t = tasks.OrderBy(t => t.CreationDate).ToList();
                        break;
                    case 2:
                        t = tasks.OrderBy(t => t.EndDate).ToList();
                        break;
                    case 3:
                        t = tasks.OrderBy(t => t.Comment).ToList();
                        break;
                    case 4:
                        t = tasks.OrderBy(t => t.Done).ToList();
                        break;
                    case 5:
                        IEnumerable<Usr> usrs = _usrContext.User.OrderBy(u=>u.Surname);
                        foreach(var u in usrs)
                        {
                            t.AddRange(tasks.FindAll(t => t.UserOwner == u.ID));
                        }
                        break;
                }
            }

            model = new MainViewModel { Task = new Task(), Tasks = t, IsActiveTaskExists = false, Users = _usrContext.User };
            return View(model);
        }

        // GET: WorkTasks/Chill
        public async Task<IActionResult> Chill()
        {
            return View();
        }
        // GET: WorkTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task
                .FirstOrDefaultAsync(m => m.ID == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // GET: WorkTasks/Create
        public IActionResult Create()
        {
            WorkTaskModel model = new WorkTaskModel();
            model.Users = _usrContext.User.ToList();
            model.Task = new Task();
            return View(model);
        }

        // POST: WorkTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CreationDate,EndDate,Comment,Type,UserOwner")] Task task)
        {
            if (ModelState.IsValid)
            {
                task.CreationDate = DateTime.Now;
                task.Type = "Работа";
                task.Done = 0;
                _context.Add(task);
                await _context.SaveChangesAsync();
                if (User.IsInRole("Администратор"))
                    return RedirectToAction("Index", "Home");
                else
                    return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: WorkTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task.FindAsync(id);
            task.Done = 2;
            _context.Update(task);
            await _context.SaveChangesAsync();
            if (task == null)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
        // GET: WorkTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task
                .FirstOrDefaultAsync(m => m.ID == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: WorkTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _context.Task.FindAsync(id);
            _context.Task.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int id)
        {
            return _context.Task.Any(e => e.ID == id);
        }
    }
}

source/repos/WTCnt/WTCnt/Views/WorkTasks/Chill.cshtml
<head>
    <link href="~/css/chill.css" rel="stylesheet" />
</head>
<body>
    <h1 style="color:darkblue">Сначала завершите отгул, а потом можно и поработать</h1>
</body>

source/repos/WTCnt/WTCnt/Views/WorkTasks/Create.cshtml
@model WTCnt.Models.WorkTaskModel

<body>
    <h1 style="text-align:center">Назначить задачу</h1>
    <hr />
    <div style="text-align: center; overflow-y: scroll; height:543px">
        <center>
            <div>
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Task.Comment" class="control-label">Задача:</label>
                            <input asp-for="Task.Comment" class="form-control" />
                            <span asp-validation-for="Task.Comment" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Task.EndDate" class="control-label">Закончить к:</label>
                            <input asp-for="Task.EndDate" class="form-control" />
                            <span asp-validation-for="Task.EndDate" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Task.UserOwner" class="control-label">Сотрудник:</label>
                            <select asp-for="Task.UserOwner" class="form-control">
                                @foreach (var item in Model.Users)
                                {
                                    <option value="@item.ID">@item.Name @item.Surname</option>
                                }
                            </select>
                            <span asp-validation-for="Task.UserOwner" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Добавить" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </center>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/WorkTasks/Delete.cshtml
@model WTCnt.Models.Task

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Task</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserOwner)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

source/repos/WTCnt/WTCnt/Views/WorkTasks/Details.cshtml
@model WTCnt.Models.Task



<h1 style="color:navy">Подбробности</h1>

<div>
    <h4 style="color:navy">Задача</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2" style="color:navy">
            Задача
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class="col-sm-2" style="color:navy">
            Создана
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="col-sm-2" style="color:navy">
            Выполнить к
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

source/repos/WTCnt/WTCnt/Views/WorkTasks/Edit.cshtml
@model WTCnt.Models.Task

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserOwner" class="control-label"></label>
                <input asp-for="UserOwner" class="form-control" />
                <span asp-validation-for="UserOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/WorkTasks/Index.cshtml
@model MainViewModel

<head>
    <script src="https://www.google.com/jsapi"></script>
    <script>
        google.load("visualization", "1", { packages: ["corechart"] });
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Газ', 'Объём'],
                ['Не выполнено', @Model.Tasks.ToList().FindAll(t=>t.Type=="Работа"&&t.Done==0).Count],
                ['Выполнено',@Model.Tasks.ToList().FindAll(t=>t.Type=="Работа"&&t.Done==2).Count],
                ['Просрочено',@Model.Tasks.ToList().FindAll(t=>t.Type=="Работа"&&t.Done==1).Count]
            ]);
            var options = {
                title: 'За последний месяц',
                is3D: false,
                pieResidueSliceLabel: 'Остальное'
            };
            var chart = new google.visualization.PieChart(document.getElementById('air'));
            chart.draw(data, options);
        }
    </script>
    <script src="~/js/nicepage.js"></script>
    <script src="~/js/site.js"></script>
    <link href="~/css/scrolltable.css" rel="stylesheet" />
</head>
<body>
    <table width="99%" align="center">
        <tbody>
            <tr>
                <td width="80%" padding="10px">
                    <div class="scroll-table">
                        <table>
                            <thead>
                                <tr>
                                    <th style="text-align:center" width="12%">
                                        <a asp-action="Index" asp-controller="WorkTasks" asp-route-id=1 style="color:aliceblue; text-align:center; font-size:12px">Дата начала</a>
                                    </th>
                                    <th style="text-align:center" width="12%">
                                        <a asp-action="Index" asp-controller="WorkTasks" asp-route-id=2 style="color: aliceblue; text-align: center; font-size: 12px">Дата окончания</a>
                                    </th>
                                    <th style="text-align:center" width="40%">
                                        <a asp-action="Index" asp-controller="WorkTasks" asp-route-id=3 style="color: aliceblue; text-align: center; font-size: 12px">Задача</a>
                                    </th>
                                    <th style="text-align:center" width="12%">
                                        <a asp-action="Index" asp-controller="WorkTasks" asp-route-id=4 style="color: aliceblue; text-align: center; font-size: 12px">Выполнено</a>
                                    </th>
                                    <th style="text-align:center" width="12%">

                                    </th>
                                    <th style="text-align:center" width="12%">

                                    </th>
                                </tr>
                            </thead>
                        </table>
                        <div class="scroll-table-body" style="height:550px">
                            <table>
                                <tbody>
                                    @foreach (var item in Model.Tasks)
                                    {
                                        <tr>
                                            <td style="text-align:center; border-style:none" width="12%">
                                                @item.CreationDate.ToString("d")
                                            </td>
                                            <td style="text-align: center; border-style: none" width="12%">
                                                @if (item.EndDate.HasValue)
                                                {
                                                    @item.EndDate.Value.ToString("d")
                                                }
                                            </td>
                                            <td style="text-align: center; border-style: none" width="40%">
                                                @Html.DisplayFor(modelItem => item.Comment)
                                            </td>
                                            <td style="text-align: center; border-style: none" width="12%">
                                                @if (item.Done == 2)
                                                {
                                                    <b style="color:green">Да</b>
                                                }
                                                else if (item.Done == 1)
                                                {
                                                    <b style="color:red">Просрочено</b>
                                                }
                                                else if (item.Done == 0)
                                                {
                                                    <b style="color:orange">Нет</b>
                                                }
                                            </td>
                                            <td style="text-align: center; border-style: none" width="12%">
                                                <a asp-action="Details" asp-route-id="@item.ID">Подробнее</a>
                                            </td>
                                            @if (item.Done == 2)
                                            {
                                                <td style="text-align: center; border-style: none" width="12%">
                                                    <b>-</b>
                                                </td>
                                            }
                                            else
                                            {
                                                <td style="text-align: center; border-style: none" width="12%">
                                                    <a asp-action="Edit" asp-route-id="@item.ID">Завершить</a>
                                                </td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </td>
               <td width="2%"></td>
                <td width="18%">
                    <center>
                        <h3>Статистика моих задач:</h3>
                        <div id="air" style="width: 350px; height: 400px;"></div>
                    </center>
                </td>
            </tr>
        </tbody>
    </table>
</body>

source/repos/WTCnt/WTCnt/Views/WorkTasks/IndexForAdmin.cshtml
@model MainViewModel

<head>
    <script src="~/js/nicepage.js"></script>
    <script src="~/js/site.js"></script>
    <link href="~/css/scrolltable.css" rel="stylesheet" />
</head>
<body>
    <div class="scroll-table">
        <table>
            <thead>
                <tr>
                    <th align="center">
                        <a asp-action="IndexForAdmin" asp-controller="WorkTasks" asp-route-id=5 style="color:aliceblue">Пользователь</a>
                    </th>
                    <th align="center">
                        <a asp-action="IndexForAdmin" asp-controller="WorkTasks" asp-route-id=1 style="color:aliceblue">Дата начала</a>
                    </th>
                    <th align="center">
                        <a asp-action="IndexForAdmin" asp-controller="WorkTasks" asp-route-id=2 style="color:aliceblue">Дата окончания</a>
                    </th>
                    <th align="center">
                        <a asp-action="IndexForAdmin" asp-controller="WorkTasks" asp-route-id=3 style="color:aliceblue">Задача</a>
                    </th>
                    <th>
                        <a asp-action="IndexForAdmin" asp-controller="WorkTasks" asp-route-id=4 style="color:aliceblue">Выполнено</a>
                    </th>
                    <th>
                        -
                    </th>
                </tr>
            </thead>
        </table>
        <div class="scroll-table-body" style="height:550px">
            <table>
                <tbody>
                    @foreach (var item in Model.Tasks)
                    {
                        <tr>
                            <td align="center">
                                @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Name @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Surname
                            </td>
                            <td align="center">
                                @item.CreationDate.ToString("d")
                            </td>
                            <td align="center">
                                @if (item.EndDate.HasValue)
                                {
                                    @item.EndDate.Value.ToString("d")
                                }
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Comment)
                            </td>
                            <td align="center">
                                @if (item.Done == 2)
                                {
                                    <b style="color:green">Да</b>
                                }
                                else if (item.Done == 1)
                                {
                                    <b style="color:red">Просрочено</b>
                                }
                                else if (item.Done == 0)
                                {
                                    <b style="color:orange">Нет</b>
                                }
                            </td>
                            <td align="center">
                                <a asp-action="Details" asp-route-id="@item.ID">Подробнее</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>