source/repos/WTCnt/WTCnt/Models/Usr.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WTCnt.Models
{
    public class Usr
    {
        public int ID { get; set; }
        public string DomenName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Role { get; set; }
        public byte[] Photo { get; set; }
    }
}

source/repos/WTCnt/WTCnt/Controllers/UsrsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WTCnt.Models;

namespace WTCnt.Controllers
{
    public class UsrsController : Controller
    {
        private readonly UsrContext _context;

        public UsrsController(UsrContext context)
        {
            _context = context;
        }

        // GET: Usrs
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }
        // GET: Usrs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usr = await _context.User
                .FirstOrDefaultAsync(m => m.ID == id);
            if (usr == null)
            {
                return NotFound();
            }

            return View(usr);
        }

        // GET: Usrs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usrs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,DomenName,Password,Name,Surname,Role,Photo")] Usr usr, IFormFile uploadImage)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (uploadImage != null)
                    using (var binaryReader = new BinaryReader(uploadImage.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)uploadImage.Length);
                    }
                usr.Photo = imageData;
                _context.Add(usr);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Usrs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usr = await _context.User.FindAsync(id);
            if (usr == null)
            {
                return NotFound();
            }
            return View(usr);
        }

        // POST: Usrs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,DomenName,Password,Name,Surname,Role,Photo")] Usr usr, IFormFile uploadImage)
        {
            if (id != usr.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    byte[] imageData = null;
                    if (uploadImage != null)
                        using (var binaryReader = new BinaryReader(uploadImage.OpenReadStream()))
                        {
                            imageData = binaryReader.ReadBytes((int)uploadImage.Length);
                        }
                    usr.Photo = imageData;
                    _context.Update(usr);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsrExists(usr.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usr);
        }

        // GET: Usrs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usr = await _context.User
                .FirstOrDefaultAsync(m => m.ID == id);
            if (usr == null)
            {
                return NotFound();
            }

            return View(usr);
        }

        // POST: Usrs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usr = await _context.User.FindAsync(id);
            _context.User.Remove(usr);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsrExists(int id)
        {
            return _context.User.Any(e => e.ID == id);
        }
    }
}

source/repos/WTCnt/WTCnt/Views/Usrs/Create.cshtml
@model WTCnt.Models.Usr


<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/css/attachfile.css" rel="stylesheet" />
</head>
<body>
    <h1 style="text-align:center">Добавить пользователя</h1>
    <hr />
    <div style="text-align: center; overflow-y: scroll; height:543px">
        <center>
            <div>
                <div class="col-md-4">
                    @using (Html.BeginForm("Create", "Usrs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="DomenName" class="control-label">Логин:</label>
                            <input asp-for="DomenName" class="form-control" />
                            <span asp-validation-for="DomenName" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Password" class="control-label">Пароль:</label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Name" class="control-label">Имя:</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Surname" class="control-label">Фамилия:</label>
                            <input asp-for="Surname" class="form-control" />
                            <span asp-validation-for="Surname" class="text-danger"></span>
                        </div>
                        <div class="form-group" style="text-align:left">
                            <label asp-for="Role" class="control-label">Роль:</label>
                            <select asp-for="Role" class="form-control">
                                <option value="Администратор">Администратор</option>
                                <option value="Ведущий программист">Ведущий программист</option>
                                <option value="Программист">Программист</option>
                                <option value="Ведущий тестировщик">Ведущий тестировщик</option>
                                <option value="Тестировщик">Тестировщик</option>
                            </select>
                            <span asp-validation-for="Role" class="text-danger"></span>
                        </div>
                        <div class="example-1">
                            <div class="form-group">
                                <label class="label">
                                    <i class="material-icons">attach_file</i>
                                    <span class="title">Добавить изображение</span>
                                    <input type="file" class="form-control" name="uploadImage" />
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Добавить" class="btn btn-primary" />
                        </div>
                    }
                </div>
            </div>
        </center>
    </div>

</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/Usrs/Delete.cshtml
@model WTCnt.Models.Usr

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usr</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DomenName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DomenName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

source/repos/WTCnt/WTCnt/Views/Usrs/Details.cshtml
@model WTCnt.Models.Usr



<h1>@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Логин
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DomenName)
        </dd>
        <dt class = "col-sm-2">
            Пароль
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            Роль
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            Фото
        </dt>
        <dd class="col-sm-10">
            @if (Model.Photo != null)
            {
                <div class="image" style="align-content:center">
                    @Html.Raw("<img style='width:100px; height:200px;' src=\"data:image/jpeg;base64,"
                                         + Convert.ToBase64String(Model.Photo) + "\" />")
                </div>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

source/repos/WTCnt/WTCnt/Views/Usrs/Edit.cshtml
@model WTCnt.Models.Usr
<head>
    <link href="~/css/attachfile.css" rel="stylesheet" />

</head>
<h1 style="text-align: center;">Редактировать</h1>
<hr />
<div style="text-align: center; overflow-y: scroll; height:543px">
    <center>
        <div>
            <div class="col-md-4">
                @using (Html.BeginForm("Edit", "Usrs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />
                    <div class="form-group" style="text-align: left;">
                        <label asp-for="DomenName" class="control-label">Логин:</label>
                        <input asp-for="DomenName" class="form-control" />
                        <span asp-validation-for="DomenName" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="text-align: left;">
                        <label asp-for="Password" class="control-label">Пароль:</label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="text-align: left;">
                        <label asp-for="Name" class="control-label">Имя:</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="text-align: left;">
                        <label asp-for="Surname" class="control-label">Фамилия:</label>
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="text-align: left;">
                        <label asp-for="Role" class="control-label">Роль:</label>
                        <select asp-for="Role" class="form-control">
                            <option value="Администратор">Администратор</option>
                            <option value="Ведущий программист">Ведущий программист</option>
                            <option value="Программист">Программист</option>
                            <option value="Ведущий тестировщик">Ведущий тестировщик</option>
                            <option value="Тестировщик">Тестировщик</option>
                        </select>
                        <span asp-validation-for="Role" class="text-danger"></span>
                    </div>
                    <div class="example-1">
                        <div class="form-group">
                            <label class="label" style="text-align:center; align-content:center">
                                <i class="material-icons">attach_file</i>
                                <span class="title" style="text-align: center; align-content: center">Добавить изображение</span>
                                <input type="file" class="form-control" name="uploadImage" />
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" style="background-color:#5a3c8d" value="Сохранить" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </center>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/Usrs/Index.cshtml
@model IEnumerable<WTCnt.Models.Usr>

<head>
    <link href="~/css/scrolltable.css" rel="stylesheet" />
</head>
<h1>Пользователи</h1>

<p>
    <a asp-action="Create" style="text-decoration: none;">
        <img src="~/files/add-user.png" />
    </a>
</p>
<div class="scroll-table">
    <table>
        <thead>
            <tr>
                <th>

                </th>
                <th style="text-align:center; color:white">
                    Имя
                </th>
                <th style="text-align: center; color: white">
                    Фамилия
                </th>
                <th style="text-align: center; color: white">
                    Роль
                </th>
                <th style="text-align: center; color: white">
                    Логин
                </th>
                <th></th>
                @if (User.IsInRole("Администратор") || User.IsInRole("Ведущий программист") || User.IsInRole("Ведущий тестировщик"))
                {
                    <th></th>
                }
            </tr>
        </thead>
    </table>
    <div class="scroll-table-body" style="height:470px">
        <table>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr style="background: linear-gradient(#FFFFFF, #FFFFF0);">
                        <td style="border-style:none;">
                            @if (item.Photo != null)
                            {
                                <div class="image" style="align-content:center;text-align:center">
                                    @Html.Raw("<img style='width:60px; height:60px; border-style:solid; border-radius:4px' src=\"data:image/jpeg;base64,"
                                                         + Convert.ToBase64String(item.Photo) + "\" />")
                                </div>
                            }
                        </td>
                        <td style="border-style:none; text-align:center">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td style="border-style:none; text-align:center">
                            @Html.DisplayFor(modelItem => item.Surname)
                        </td>
                        <td style="border-style:none; text-align:center">
                            @Html.DisplayFor(modelItem => item.Role)
                        </td>
                        <td style="border-style:none; text-align:center">
                            @Html.DisplayFor(modelItem => item.DomenName)
                        </td>
                        <td style="border-style:none; text-align:center">
                            <div>
                                <a asp-action="Edit" asp-route-id="@item.ID">
                                    <img src="~/files/compose_edit_modify_icon_177770.png" />&nbsp;
                                </a>
                                <a asp-action="Details" asp-route-id="@item.ID">
                                    <img src="~/files/information.png" />&nbsp;
                                </a>
                                <a asp-action="Delete" asp-route-id="@item.ID">
                                    <img src="~/files/delete.png" />
                                </a>
                            </div>
                        </td>
                        @if (User.IsInRole("Администратор") || User.IsInRole("Ведущий программист") || User.IsInRole("Ведущий тестировщик"))
                        {
                            <td style="border-style:none; text-align:center">
                                <a asp-action="EmployeeStatistic" asp-controller="Account" asp-route-id="@item.ID">Статистика сотрудника</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>