source/repos/WTCnt/WTCnt/Models/Prject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WTCnt.Models
{
    public class Prject
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime CreationDate { get; set; }
        public int UserOwner { get; set; }
    }
}

source/repos/WTCnt/WTCnt/Controllers/PrjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Timers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WTCnt.Models;

namespace WTCnt.Controllers
{
    public class PrjectsController : Controller
    {
        private readonly PrjectContext _context;
        private readonly UsrContext _usrContext;
        private readonly MessageContext messageContext;
        private readonly ProjectPerTaskContext _ppuContext;
        private readonly TaskContext _tContext;
        public static int prid;
        public PrjectsController(PrjectContext context, UsrContext usr, ProjectPerTaskContext ppu, MessageContext mc, TaskContext t)
        {
            messageContext = mc;
            _context = context;
            _usrContext = usr;
            _ppuContext = ppu;
            _tContext = t;
        }
        //[Authorize(Roles = "Ведущий программист,Администратор")]
        // GET: Prjects
        public async Task<IActionResult> Index()
        {
            ProjectsViewModel model = new ProjectsViewModel();
            model.Users = _usrContext.User;
            model.Prjects = await _context.Project.ToListAsync();
            model.messages = messageContext.Message;
            return View(model);
        }
        public async Task<IActionResult> ViewForUser()
        {
            ProjectsViewModel model = new ProjectsViewModel();
            model.Users = _usrContext.User;
            model.Prjects = await _context.Project.ToListAsync();
            model.messages = messageContext.Message;
            model.ProjectPerTasks = _ppuContext.ProjectPerTasks.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult Chat()
        {
            ProjectsViewModel empList = new ProjectsViewModel();;
            empList.Users = _usrContext.User;
            empList.messages = messageContext.Message;
            return PartialView("_Chat",empList);
        }
        // GET: Prjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prject = await _context.Project
                .FirstOrDefaultAsync(m => m.ID == id);
            if (prject == null)
            {
                return NotFound();
            }
            ProjectsViewModel model = new ProjectsViewModel();
            model.ProjectPerTasks = _ppuContext.ProjectPerTasks.ToList().FindAll(ppu => ppu.ID_project == id);
            model.tasks = new List<Models.Task>();
            foreach (ProjectPerTask perTask in model.ProjectPerTasks)
                model.tasks.Add(_tContext.Task.ToList().Find(x=>x.ID==perTask.ID_Task));
            model.Users = _usrContext.User;
            model.Prject = prject;
            model.messages = messageContext.Message;
            prid = (int)id;
            return View(model);
        }

        // GET: Prjects/Create
        public IActionResult Create()
        {
            ProjectsViewModel model = new ProjectsViewModel();
            model.Users = _usrContext.User;
            return View(model);
        }

        // POST: Prjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,EndDate,CreationDate,UserOwner")] Prject prject)
        {
            if (ModelState.IsValid)
            {
                prject.CreationDate = DateTime.Now;
                _context.Add(prject);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "ProjectPerTasks", new { pId = prject.ID });
            }
            return View(prject);
        }

        // GET: Prjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prject = await _context.Project.FindAsync(id);
            if (prject == null)
            {
                return NotFound();
            }
            return View(prject);
        }

        // POST: Prjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,EndDate,CreationDate,UserOwner")] Prject prject)
        {
            if (id != prject.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrjectExists(prject.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prject);
        }

        // GET: Prjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prject = await _context.Project
                .FirstOrDefaultAsync(m => m.ID == id);
            if (prject == null)
            {
                return NotFound();
            }

            return View(prject);
        }

        // POST: Prjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prject = await _context.Project.FindAsync(id);
            _context.Project.Remove(prject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrjectExists(int id)
        {
            return _context.Project.Any(e => e.ID == id);
        }
        [HttpPost]
        public async Task<EmptyResult> SendMessage([Bind("messText")] string messText)
        {
            Message message = new Message();
            message.Text = messText;
            message.TimeSend = DateTime.Now;
            message.User_ID = int.Parse(User.Identities.ToList()[0].Name);
            message.Project_ID = prid;
            messageContext.Add(message);
            await messageContext.SaveChangesAsync();
            return new EmptyResult();
        }
    }
}

source/repos/WTCnt/WTCnt/Views/Prjects/Create.cshtml
@model WTCnt.Models.ProjectsViewModel

<head>

</head>
<body>
    <div style="text-align:center">
        <center>
            <h1>Добавить проект</h1>
            <hr />
            <div>
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Prject.Name" class="control-label">Имя</label>
                            <input asp-for="Prject.Name" class="form-control" />
                            <span asp-validation-for="Prject.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Prject.EndDate" class="control-label">Срок сдачи</label>
                            <input asp-for="Prject.EndDate" class="form-control" />
                            <span asp-validation-for="Prject.EndDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Prject.UserOwner" class="control-label">Руководитель</label>
                            <select asp-for="Prject.UserOwner" class="form-control">
                                @foreach (var item in Model.Users)
                                {
                                    <option value="@item.ID">@item.Name @item.Surname</option>
                                }
                            </select>
                            <span asp-validation-for="Prject.UserOwner" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Добавить" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </center>
    </div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/Prjects/Delete.cshtml
@model WTCnt.Models.Prject



<h3>Вы уверены, что хотите удалить этот проект?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Проект
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

source/repos/WTCnt/WTCnt/Views/Prjects/Details.cshtml
@model WTCnt.Models.ProjectsViewModel

<head>
    <link href="~/css/scroll.css" rel="stylesheet" />
    <link href="~/css/buttoninput.css" rel="stylesheet" />
    <script src="~/js/nicepage.js"></script>
    <script src="~/js/site.js"></script>
    <script src="https://www.google.com/jsapi"></script>
    <script>
        google.load("visualization", "1", { packages: ["corechart"] });
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Газ', 'Объём'],
                ['Выполнено', @Model.tasks.FindAll(t=>t.Done==0).Count],
                ['Не выполнено',@Model.tasks.FindAll(t => t.Done == 2).Count],
            ]);
            var options = {
                title: 'Степень выполнения проекта',
                is3D: false,
                pieResidueSliceLabel: 'Остальное'
            };
            var chart = new google.visualization.PieChart(document.getElementById('air'));
            chart.draw(data, options);
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/jscript">
        function CreateMergeReport() {
            var messText = $('#mtext').val();
            $.post("/Prjects/SendMessage", { messText: messText });
            $("#form0").trigger('reset');
        };
    </script>
    <script type="text/javascript">
        setInterval(function () {
            $.ajax({
                url: '/Prjects/Chat',
                datatype: "json",
                type: "post",
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    $("#empList").html(data);
                },
                error: function (xhr) {
                    alert('error');
                }
            });
        }, 3000);
    </script>
</head>
<body>
    <h1>@Model.Prject.Name</h1>
    <table>
        <tr>
            <td>
                <div>
                    <dl class="row">
                        <dt class="col-sm-2">
                            Создан
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Prject.CreationDate)
                        </dd>
                        <dt class="col-sm-2">
                            Срок до
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Prject.EndDate)
                        </dd>
                        <dt class="col-sm-2">
                            Руководитель
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Users.ToList().Find(u => u.ID == Model.Prject.UserOwner).Name @Model.Users.ToList().Find(u => u.ID == Model.Prject.UserOwner).Surname
                        </dd>
                        <dt class="col-sm-10">
                            Участники
                        </dt>
                    </dl>
                    <div style="height:100px; overflow-y:scroll">
                        @foreach (var item in Model.tasks)
                        {
                            <div>
                                @Html.Raw("<img style='width:50px; height:50px; border-radius:10px; border-style:solid' alt='photo'  src=\"data:image/jpeg;base64,"
                                                                 + Convert.ToBase64String(Model.Users.ToList().Find(u => u.ID == item.UserOwner).Photo) + "\" />")
                                @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Name @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Surname
                            </div>
                        }
                    </div>
                </div>
                <div id="air" style="width: 500px; height: 400px;"></div>
            </td>
            <td>
                <div id="empList">
                </div>
                @using (Html.BeginForm())
                {
                    <div class="u-form-horizontal" id="form0">

                        <label>
                            <input class="text-field__input" input type="text" style="height:30px" name="mtext" id="mtext">
                        
                        <button class="btn-dark" style="height:inherit" onclick="CreateMergeReport()" type="button">Отправить</button>
                        </label>
                    </div>
                }
            </td>
        </tr>
    </table>
</body>

source/repos/WTCnt/WTCnt/Views/Prjects/Edit.cshtml
@model WTCnt.Models.Prject

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Prject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserOwner" class="control-label"></label>
                <input asp-for="UserOwner" class="form-control" />
                <span asp-validation-for="UserOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/repos/WTCnt/WTCnt/Views/Prjects/Index.cshtml
@model ProjectsViewModel

<head>
    <link href="~/css/scrolltable.css" rel="stylesheet" />
</head>
<body>
    @if (User.IsInRole("Администратор")|| User.IsInRole("Ведущий программист")|| User.IsInRole("Ведущий тестировщик"))
    {
        <h1>Проекты <a asp-action="Create" style="font-size:40px">&#10010;</a></h1>
    }
    else
    {
        <h1>Проекты</h1>
    }

    <div class="scroll-table">
        <table>
            <thead>
                <tr>
                    <th align="center">
                        Название
                    </th>
                    <th align="center">
                        Срок сдачи
                    </th>
                    <th align="center">
                        Создан
                    </th>
                    <th align="center">
                        Тимлид
                    </th>
                    <th></th>
                </tr>
            </thead>
        </table>
        <div class="scroll-table-body">
            <table>
                <tbody>
                    @foreach (var item in Model.Prjects)
                    {
                        <tr>
                            <td align="center">
                                <a asp-action="Details" asp-route-id="@item.ID">@Html.DisplayFor(modelItem => item.Name)</a>
                            </td>
                            <td align="center">
                                @item.EndDate.ToShortDateString()
                            </td>
                            <td align="center">
                                @item.CreationDate.ToShortDateString()
                            </td>
                            <td align="center">
                                @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Name @Model.Users.ToList().Find(u => u.ID == item.UserOwner).Surname
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ID">
                                    <img src="~/files/compose_edit_modify_icon_177770.png" />
                                </a>
                                <a asp-action="Delete" asp-route-id="@item.ID">
                                    <img src="~/files/delete.png" />
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

source/repos/WTCnt/WTCnt/Views/Prjects/ViewForUser.cshtml
@model ProjectsViewModel


<h1>Проекты</h1>
<head>
    <link href="~/css/table.css" rel="stylesheet" />
    <link href="~/css/gradient.css" rel="stylesheet" />
</head>
<body>
    <p>
        <a asp-action="Create">Добавить</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <td align="center">
                    Название
                </td>
                <td align="center">
                    Создан
                </td>
                <td align="center">
                    Тимлид
                </td>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProjectPerTasks@*.FindAll(p => p.ID_Task == int.Parse(User.Identities.ToList()[0].Name))*@)
            {
                <tr>
                    <td align="center">
                        @Html.DisplayFor(modelItem => Model.Prjects.ToList().Find(p => p.ID == item.ID_project).Name)
                    </td>
                    <td align="center">
                        @Model.Prjects.ToList().Find(p => p.ID == item.ID_project).EndDate.ToShortDateString()
                    </td>
                    <td align="center">
                        @Model.Users.ToList().Find(u => u.ID == Model.Prjects.ToList().Find(p => p.ID == item.ID_project).UserOwner).Name @Model.Users.ToList().Find(u => u.ID == Model.Prjects.ToList().Find(p => p.ID == item.ID_project).UserOwner).Surname
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID_project">Завершить</a>
                    </td>
                    @*<td>
                        <a asp-action="Details" asp-controller="Prjects" asp-route-id="@Model.Prjects.ToList().Find(p => p.ID == item.ID_project).ID">Подробнее</a>
                    </td>*@
                </tr>
            }
        </tbody>
    </table>
</body>

source/repos/WTCnt/WTCnt/Views/Prjects/_Chat.cshtml
@model WTCnt.Models.ProjectsViewModel


<head>
    <link href="~/css/scroll.css" rel="stylesheet" />
</head>
<body>
    <div style="height:490px; width:300px; overflow-y:scroll; border-style:solid; background-color:cornsilk">
        @foreach (var item in Model.messages)
        {
            @if (int.Parse(User.Identities.ToList()[0].Name) != item.User_ID)
            {
                <div style="background-color: #5a3c8d; color:white; border-radius: 15px; margin: 5px; text-align: left ">
                    <label style="vertical-align:central">
                        @Html.Raw("<img style='width:50px; height:50px; border-radius:90px; margin: 3px' alt='photo'  src=\"data:image/jpeg;base64,"
                                                + Convert.ToBase64String(Model.Users.ToList().Find(u => u.ID == item.User_ID).Photo) + "\" />")
                        @item.Text
                    </label>
                </div>
            }
            else
            {
                <div style="background-color: #f08b1b; color: white; border-radius: 15px; margin: 5px; text-align: right ">
                    <label style="vertical-align:central">
                        @item.Text
                        @Html.Raw("<img style='width:50px; height:50px; border-radius:90px; margin: 3px' alt='photo'  src=\"data:image/jpeg;base64,"
                                                + Convert.ToBase64String(Model.Users.ToList().Find(u => u.ID == item.User_ID).Photo) + "\" />")
                    </label>
                </div>
            }
        }
    </div>
</body>

source/repos/WTCnt/WTCnt/Views/Prjects/_SendMessage.cshtml
@model WTCnt.Models.ProjectsViewModel


<head>
    <link href="~/css/chat.css" rel="stylesheet" />

</head>
<body>
    <div class="chat">
        <h1 class="chat__header">Chat</h1>
        <div class="chat__content">
            @foreach (var item in Model.messages)
            {
                @if (int.Parse(User.Identities.ToList()[0].Name) == item.User_ID)
                {
                    <div class="chat__item">
                        @Html.Raw("<img style='width:50px; height:50px;' alt='photo' class='chat__person - avatar' src=\"data:image/jpeg;base64,"
                                                + Convert.ToBase64String(Model.Users.ToList().Find(u => u.ID == item.User_ID).Photo) + "\" />")
                        <div class="chat__messages">
                            <div class="chat__message">
                                <div class="chat__message-time">
                                    @item.TimeSend.ToString("U")
                                </div>
                                <div class="chat__message-content">
                                    @item.Text
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="chat__item chat__item--responder">
                        @Html.Raw("<img style='width:50px; height:50px;' alt='photo' class='chat__person - avatar' src=\"data:image/jpeg;base64,"
                                        + Convert.ToBase64String(Model.Users.ToList().Find(u => u.ID == item.User_ID).Photo) + "\" />")
                        <div class="chat__messages">
                            <div class="chat__message">
                                <div class="chat__message-time">
                                    @item.TimeSend.ToString("U")
                                </div>
                                <div class="chat__message-content">
                                    @item.Text
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</body>

source/repos/WTCnt/WTCnt/Views/Prjects/d.cshtml
<!--It's just a concept, a chat UI design for direct messaging!
Enjoy! :) Don't forget to click the heart if you like it! -->

<head>
    <script>
        $(".person").on('click', function () {
            $(this).toggleClass('focus').siblings().removeClass('focus');
        })
    </script>
    <link href="~/css/chatcss.scss" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="chatbox">
            <div class="top-bar">
                <div class="avatar"><p>V</p></div>
                <div class="name">Voldemort</div>
                <div class="icons">
                    <i class="fas fa-phone"></i>
                    <i class="fas fa-video"></i>
                </div>
                <div class="menu">
                    <div class="dots"></div>
                </div>
            </div>
            <div class="middle">
                <div class="voldemort">
                    <div class="incoming">
                        <div class="bubble">Hey, Father's Day is coming up..</div>
                        <div class="bubble">What are you getting.. Oh, oops sorry dude.</div>
                    </div>
                    <div class="outgoing">
                        <div class="bubble lower">Nah, it's cool.</div>
                        <div class="bubble">Well you should get your Dad a cologne. Here smell it. Oh wait! ...</div>
                    </div>
                    <div class="typing">
                        <div class="bubble">
                            <div class="ellipsis one"></div>
                            <div class="ellipsis two"></div>
                            <div class="ellipsis three"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom-bar">
                <div class="chat">
                    <input type="text" placeholder="Type a message..." />
                    <button type="submit"><i class="fas fa-paper-plane"></i></button>
                </div>
            </div>
        </div>
        <div class="messages"></div>
        <div class="profile">
            <div class="avatar"><p>H</p></div>
            <div class="name2">Harry<p class="email">Harry@potter.com</p></div>
        </div>
        <ul class="people">
            <li class="person focus">
                <span class="title">Voldemort </span>
                <span class="time">2:50pm</span><br>
                <span class="preview">What are you getting... Oh, oops...</span>
            </li>
            <li class="person">
                <span class="title">Ron</span>
                <span class="time">2:25pm</span><br>
                <span class="preview">Meet me at Hogsmeade and bring...</span>
            </li>
            <li class="person">
                <span class="title">Hermione</span>
                <span class="time">2:12pm</span><br>
                <span class="preview">Have you and Ron done your hom...</span>
            </li>
        </ul>
    </div>

    <footer>
        <p>made by <a href="https://codepen.io/juliepark"> julie</a> ♡
    </footer>
</body>